gazebo_ros_control:
  pid_gains:
    joint1:
      p: 100
      i: 1
      d: 0
    joint2:
      p: 100
      i: 1
      d: 0.1
    joint3:
      p: 100
      i: 1
      d: 0.1
    joint4:
      p: 100
      i: 1
      d: 0.1